### PR TITLE
Infer command string directly from sys argv

### PR DESCRIPTION
**Pull request by tsalo**
Closes None. You may not want to merge this, but I think it could be really useful in two respects: (1) it decreases your maintenance burden, since changes to the CLI don't need to be reflected in the command string composed within the function and (2) it makes using the function directly more straightforward.

Changes proposed in this pull request:

- Add a `command_str` parameter to the pySPFM workflow function.
- Compile the `command_str` directly from `sys.argv` within `_main()`.
- Drop `argv` parameter from `_main()` and `parse_args`. AFAICT it doesn't actually do anything. It's just always None.
- Add `pytest-console-scripts` to test dependencies.

### CODE REVIEW

**Comment by tsalo** [comment]
Odd new exception:

```
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/py3.10_env/bin/pySPFM", line 33, in <module>
    sys.exit(load_entry_point('pySPFM', 'console_scripts', 'pySPFM')())
  File "/opt/miniconda-latest/envs/py3.10_env/bin/pySPFM", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/opt/conda/envs/py3.10_env/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/opt/conda/envs/py3.10_env/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pySPFM
```

I'm not sure why the CircleCI node can't call pySPFM.

**Comment by eurunuela** [comment]
Thank you @tsalo! I'm more than happy to merge this. I'll have a look at the tests cause I feel like I've seen this error before.

**Comment by tsalo** [comment]
Thanks! If you're comfortable tackling the tests in a separate PR, then that works for me. If you do manage to fix them, let me know. I think we could use this in tedana as well.

**Comment by eurunuela** [comment]
> Thanks! If you're comfortable tackling the tests in a separate PR, then that works for me. If you do manage to fix them, let me know. I think we could use this in tedana as well.

I totally agree. I believe it is very useful to have the exact command to reproduce the results. I believe I actually opened a PR to add this to the reports, but never really finished it.

**Comment by tsalo** [comment]
Thanks for reminding me of your tedana PR! I've started following up there.

**Comment by eurunuela** [comment]
The integration tests fail for me with this error:

```
E       fixture 'script_runner' not found
>       available fixtures: anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, coef_path_results, cov, doctest_namespace, fista_results, hrf_file, hrf_linear_file, mask_five_echo, monkeypatch, nih_five_echo_1, no_cover, pylops_results, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, sim_data, sim_hrf, skip_integration, testpath, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

Do you get this error when running on local @tsalo ?

**Comment by tsalo** [comment]
No, but I had to install `pytest-console-scripts` first. The error I got locally was related to not having AFNI installed, so I took it to mean that it was broadly working. I'm still not sure why my local copy has access to `pySPFM` (the CLI), but CircleCI doesn't.

**Comment by eurunuela** [comment]
For some reason my pip install command was installing `pytest-console-scripts`.

It works locally for me now.

**Comment by eurunuela** [comment]
Is it possible that the tests are failing because the environment is not forcing a fresh install of `pySPFM`?

**Comment by tsalo** [comment]
Based on the CircleCI config file, it seems like it should install pySPFM each time, regardless of whether there's a cache or not, but I could be misreading it.

**Comment by tsalo** [comment]
That's awesome! Please do!

**Pull request merged**
